### ISSUE TITLE
Could not read from remote repository

### ISSUE THREAD

**Issue by mlgmlg** [fami2u/fami-plugin-lists#1]
Warning: Permanently added the RSA host key for IP address '192.30.252.122' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

怎么，插件不是公开的吗？还需要公钥 ？权限？

**Comment by devqin** [comment]
使用https协议clone项目.

 `git clone https://github.com/fami2u/fami-plugin-lists.git`

ps.如果对支付宝插件感兴趣，可查看我们的[支付宝插件](https://github.com/fami2u/cordova-plugin-weipay)
